### ISSUE TITLE
this looks familiar

### ISSUE THREAD

**Issue by nickdesaulniers** [jserv/jit-construct#4]
It's neat what you did to extend the code (ARM back end, dynasm): http://wiki.csie.ncku.edu.tw/embedded/summer2015/jit-compiler.pdf but it's weird to see someone to wholesale copy pasta most of blog post with a footnote at the end.

**Comment by jserv** [comment]
@nickdesaulniers, I made a mistake that I didn't mention your work in each slide in file jit-compiler.pdf, which was initially used for short-term training course in a rush. I will rewrite the presentation materials with proper credit notation.

**Comment by nickdesaulniers** [comment]
Also, it would be nice if you could link to the original blog post and source code in a readme in this repo.  That would mean a lot to me.  I appreciate you taking the time to do so.

**Comment by jserv** [comment]
Sure! The files README and LICENSE are added now. After ARM JIT backend is integrated, the slides will be revised with proper source link inclusion. Thanks a lot for pointing me.

**Comment by nickdesaulniers** [comment]
Cool thanks! You don't have to make note of the original license, the choice is yours!  Are you using this to teach a class? or co workers?

**Comment by jserv** [comment]
@nickdesaulniers, Yes, I am a university lecturer on [operating systems and compilers](http://wiki.csie.ncku.edu.tw/embedded/schedule). I use your blog materials as the practice for [building virtual machines](http://www.slideshare.net/jserv/vm-construct). You can see some contributors who forked and modified this repository. They are mainly the students who participate the summer course.

**Comment by nickdesaulniers** [comment]
That's neat! Would you like it if I sent your class some Firefox stickers? If so, feel free to check the git log of the original source code for my email address where you can reach me.  Email me the address for your class and I can send a bunch of stickers!
